version: '3'
services:
  db:
    image: postgres
    container_name: django-react-docker-heroku-db
  django-react-docker-heroku:
    build:
      context: .
      dockerfile: ./docker/Docker.server/Dockerfile
    image: django-react-docker-heroku
    env_file: .env
    container_name: django-react-docker-heroku
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db:postgres
